apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: instances.mysql.group
spec:
  scope: Namespaced
  group: mysql.group
  names:
    kind: Instance
    plural: instances
    singular: instance
    shortNames:
      - mysql
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              mysql_password:
                type: string
              replicas:
                type: integer
                minimum: 1
                maximum: 10
                default: 1
              labels:
                type: string
                items:
                  type: string
    additionalPrinterColumns:
    - name: Replicas
      type: string
      description: The number of replicas
      jsonPath: .spec.replicas
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
