apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: instances.mysql.group
spec:
  scope: Namespaced
  group: mysql.group
  names:
    kind: Instance
    plural: instances
    singular: instance
    shortNames:
      - mysql
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              mysql_password:
                type: string
            required:
            - mysql_password
    additionalPrinterColumns:
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
