apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.mysql.group
spec:
  scope: Namespaced
  group: mysql.group
  names:
    kind: Database
    plural: databases
    singular: database
    shortNames:
      - db
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              instance:
                type: string
              databaseName:
                type: string
    additionalPrinterColumns:
    - name: Instance
      type: string
      description: The MySQL instance
      jsonPath: .spec.instance
    - name: DatabaseName
      type: string
      description: The Database name
      jsonPath: .spec.databaseName
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
