apiVersion: batch/v1
kind: Job
metadata:
  name: db-create
spec:
  template:
    spec:
      containers:
      - name: db-create
        image: mysql
        command:
        - sh
        - -c
        - >
           mysql -h red-instance -p 123456;
           CREATE DATABASE test;
      restartPolicy: Never
